### ISSUE TITLE
Fornecer XML por parâmetro

### ISSUE THREAD

**Issue by davicastrocv** [ricardo-ropelli/lambda-nf-pdf-generator#1]
Boa tarde, 

Estou com um problema que não consigo solucionar de maneira alguma, se puder me auxiliar:

Como passo o XML como parâmetro para o relatório? Já consegui passar ele através da criação de um Data Adapter do tipo XML Document, porém só consigo gerar uma DANFE dessa maneira. Gostaria de poder passar o caminho do XML (ou o próprio XML) como parâmetro, dessa forma sempre quando eu for gerar o relatório (a DANFE no caso) seria solicitado o caminho do XML (ou o próprio XML) para que o relatório (DANFE) fosse gerado com base nos dados do XML fornecido como parâmetro.

**Comment by ricardo-ropelli** [comment]
@davicastrocv de uma olhada no readme / fonte. Como faz tempo que não uso ele, o que me lembro é que buscamos o XML no banco de dados, como mostra o fluxo. Caso não te atenda, sugiro fazer um fork atualizando para sua necessidade.

**Comment by davicastrocv** [comment]
Já baixei o projeto, já testei e funciona normalmente, mas o que preciso é fornecer o XML ou o caminho do XML como parâmetro no momento que eu eu rodo o relatório, ou ainda fornecer o XML da forma a seguir:

public function xmlToPdf()
    {
        $output = public_path() . '/report/'.time().'_CancelAck';
        $ext = "pdf";
        $data_file = public_path() . '/report/CancelAck.xml';
        $driver = 'xml';
        $xml_xpath = '/CancelResponse/CancelResult/ID';
        
        $php_jasper = new JasperPHP;
        
        $php_jasper->process(
            public_path() . '/report/CancelAck.jrxml',
            $output,
            array($ext),
            array(),
            array('data_file' => $data_file, 'driver' => $driver, 'xml_xpath' => $xml_xpath))->execute();
    
        header('Content-Description: File Transfer');
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename='.time().'_CancelAck.'.$ext);
        header('Content-Transfer-Encoding: binary');
        header('Expires: 0');
        header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        header('Content-Length: ' . filesize($output.'.'.$ext));
        flush();
        readfile($output.'.'.$ext);
        unlink($output.'.'.$ext);
    }

Fonte: https://github.com/copam/phpjasper
